### PR TITLE
Darasouza - fixing token integration

### PR DESCRIPTION
**Pull request by darasms**

### CODE REVIEW

**Review by janainaim — APPROVED** [review]

**Review by janainaim — APPROVED** [review]

**Review by janainaim — APPROVED** [review]

**Review by janainaim — APPROVED** [review]

**Review by janainaim — COMMENTED** [review]
Aprovado!

**Review by gabrielbillVG — APPROVED** [review]
approved

**Review by gabrielbillVG — APPROVED** [review]
approved

**Review by gabrielbillVG — APPROVED** [review]
approved

**Review by gabrielbillVG — APPROVED** [review]
approved

**Review by gabrielbillVG — APPROVED** [review]

**Pull request merged**
